import Navbar from '@/components/Navbar'
import '@/app/globals.css'
import { Gabarito } from 'next/font/google'

const gabarito = Gabarito({ subsets: ['latin'] })

export const metadata = {
<<<<<<< HEAD
  title: 'Home',
  description: 'Generated by create next app',
=======
  title: 'CuyAnimeList',
  description: 'Website Anime Indonesia',
>>>>>>> 5563495fbdb582855e28429d8573a666c6c1d3db
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${gabarito.className} bg-color-dark`} suppressHydrationWarning={true}>
        <Navbar />
        {children}
      </body>
    </html>
  )
}
